import java.util.concurrent.Semaphore
Semaphore mutex = new Semaphore(0)
 Thread.start {
    while(true){
    print("A");
    mutex.release()
    print("B");
    print("C");
    print("D");
    }
 }
 Thread.start {
    while(true){
    print("E");
    mutex.acquire()
    print("F");
    print("G");
    }
 }
 Thread.start {
    while(true){
    print("H");
    print("I");
    }
 }

/*
EAHIFGEBCDHAIBHFIHCDIABCDABCDABCDABCDABCDABCDABCDABCDABCDHAGIBEHCIDHAIBHIHIHIFGEFGEFGEFGEFGEFGEFGEFGECFDHAIHBICHIH
IHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIGHIHIHIHIHIHIHDIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHE
IAHFBICDAGHIBHEFGECIHIHIHIHIHIFHDAIGBCDAEBFCGDEAFBGCEDABCDABCDABCDFAGBCDABCDABHCDABCDABCDABCDABCDABCDABCDABCDABCDAB
CDAEIBCDABCDABCDABCDABCDABCFDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDAB
CDAHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIBCDABCDABCDABCDGABECFDGAEBCFDGAEBFCGDEHFAIGHEIH
FIGHEIHFIGHEIHFIGHEIFHGIEHIFHGIEHIFHGIEHIFHGIEFGEHFGEFGIEHFIGHEIBFCHGDIEAHFIBGHCEDIAFHGBIECHDIFAHGBIECHFIDGHAEIFGEH
FIBGHCEIDHFAIGHBEICFHDGIAEHBFICGHDEIAFHBGICEHDFIAGHBEICHFDIGAHEBIFCHGDIEAHFIBGHCEIDFHGIEHFIGEFGEFGEFGEFGEFGEFGEFGE
FGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDA
BCDABCDABCDABCDABCHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHDABCDABCIHIH
IHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHI
HIHIHIHFDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDAGEBCDABCDABCDABCDABCDABCDABCDABCDABCFDGAEBFCGDEAFGBECFDGAEBF
CGDEAFGBECDABCDABCDABCDABCDABCDAFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFGEFG
EFGEFGEFGEFGEFGEIHIHIHIHIHIHIHBCDABCDABIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIHIH
IHIHIHIHIHIHIHIHIHIHIHIHIHIHIFHGIEHIHFIGHEICHFDGEFGEFGEIAFBCGDEAFBGEFGEHCDABCDABCIDABCDABCDABCDABCDABCDABCDABCDA

*/